#!/usr/bin/env python3
"""Generate docs/API.md from the verified declarations in dist/Physics2D.objobasic.

The distribution file is the single shipped source of the module's public
declarations, and every member carries the `##` documentation comment the
compiler enforces. This generator assembles those verified declarations into
the reference document; prose lives in the curated category map below so a
regeneration keeps the narrative while refreshing every declaration.

Usage: python3 tools/generate_api_docs.py
Exits non-zero when a curated class is missing from the dist (which means the
document would publish aspirational or stale names).
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DIST = REPO / "dist" / "Physics2D.objobasic"
OUTPUT = REPO / "docs" / "API.md"

INTRO = """<!-- Generated by tools/generate_api_docs.py from dist/Physics2D.objobasic. Do not edit the declaration sections by hand; change the module source and regenerate. -->

# Physics2D API Reference

Physics2D is a native Objo implementation of the Box2D 3.1.1 rigid-body
physics engine. Add the generated module `dist/Physics2D.objobasic` to an
Objo Studio project as Shared Code (or a module import) and consume it with:

```objo
Import Physics2D
```

## Conventions

- **Units.** Metres, kilograms, seconds, and radians. There is no hidden
  Y-axis inversion: Objo's screen coordinates grow downward, so screen
  demos use positive-Y gravity and Y-up applications use negative-Y
  gravity.
- **Gravity is explicit.** `New World()` has zero gravity; pass
  `World.WithGravity(New Vector2(0.0, -10.0))` or set `World.Gravity`.
- **Fixed timestep.** Call `World.StepWorld(1.0 / 60.0)` once per frame
  from an accumulator loop. The default four substeps match upstream;
  the overload accepts an explicit positive substep count.
- **Facades and lifetime.** `Body`, `Shape`, `Chain`, and the joint
  facades are friendly handles over dense indexed stores. They never own
  engine state; destroying a body invalidates its facades, and
  `IsValid()` reports a stale handle. Store facades freely, but do not
  retain geometry objects (vectors, manifolds, vertices) across calls
  that document them as reused views.
- **Allocation.** After a short warm-up, `World.StepWorld` allocates
  nothing on the normal path. Reusable records (`WorldCounters`,
  `WorldProfile`, `WorldEvents`, query hit lists) are views the next call
  overwrites. Debug drawing and event snapshots are documented cold paths
  that allocate.
- **Events.** Enable per shape with the shape or body event enablers,
  then read the batched `World.Events` view after the step. Callbacks
  (custom filter, pre-solve, material mixers) are explicit opt-ins with
  no overhead while unset.
- **Determinism.** Same construction order, same inputs, same results.
  Traversal order is stable wherever the algorithm permits.

## Categories

| Section | Contents |
|---|---|
| World and stepping | The `World` facade, settings, statistics, profile, and events |
| Bodies, shapes, and chains | Definitions, facades, and geometry value types |
| Joints | All eight joint families with their definitions |
| Queries and movers | Overlaps, rays, shape casts, and capsule movers |
| Sensors and collision events | Event callbacks and material hooks |
| Explosions | Radial impulse scenes |
| Debug drawing | `World.DrawDebug`, options, colours, and the renderer interface |
| Module constants | The module-level release version |
| Internal infrastructure | Engine-owned classes that applications normally never touch |
"""

# Curated category assignment: section title -> class names in display order.
# Every name must exist in the dist; the generator enforces this.
CATEGORIES = [
    ("World and stepping", [
        "World",
        "WorldSettings",
        "WorldCounters",
        "WorldProfile",
        "WorldEvents",
    ]),
    ("Bodies, shapes, and chains", [
        "BodyDefinition",
        "Body",
        "BodyType",
        "ShapeDefinition",
        "Shape",
        "ShapeType",
        "SurfaceMaterial",
        "Filter",
        "ChainDefinition",
        "Chain",
        "ChainNormalType",
        "Circle",
        "Capsule",
        "Polygon",
        "Segment",
        "ChainSegment",
        "MassData",
        "Transform",
        "Rot",
        "AABB",
    ]),
    ("Joints", [
        "Joint",
        "DistanceJointDefinition",
        "DistanceJoint",
        "MouseJointDefinition",
        "MouseJoint",
        "MotorJointDefinition",
        "MotorJoint",
        "RevoluteJointDefinition",
        "RevoluteJoint",
        "PrismaticJointDefinition",
        "PrismaticJoint",
        "WeldJointDefinition",
        "WeldJoint",
        "WheelJointDefinition",
        "WheelJoint",
        "FilterJointDefinition",
        "FilterJoint",
        "JointType",
    ]),
    ("Queries and movers", [
        "QueryFilter",
        "ShapeProxy",
        "ShapeHit",
        "ShapeHitList",
        "TreeStats",
        "WorldOverlapCallback",
        "WorldCastCallback",
        "WorldMoverPlaneCallback",
        "Capsule",
        "Mover",
        "PlaneResult",
    ]),
    ("Sensors and collision events", [
        "CustomContactFilter",
        "CustomPreSolve",
        "CustomMaterialMixer",
        "Manifold",
        "ManifoldPoint",
    ]),
    ("Explosions", [
        "ExplosionDefinition",
    ]),
    ("Debug drawing", [
        "DebugDrawOptions",
        "DebugRenderer",
        "DebugColors",
    ]),
]

def parse_dist():
    """Parses the dist into ordered class records with member docs."""
    lines = DIST.read_text().splitlines()
    classes = {}
    order = []
    i = 0
    n = len(lines)
    while i < n:
        stripped = lines[i].strip()
        header = re.match(r"^(?:Abstract )?(?:Class|Enum) ([A-Za-z_][A-Za-z0-9_]*)", stripped)
        if not header:
            i += 1
            continue
        name = header.group(1)
        is_enum = "Enum" in stripped
        is_abstract = "Abstract" in stripped
        # Collect the leading '#' comment block above the declaration.
        doc_lines = []
        j = i - 1
        while j >= 0 and lines[j].strip().startswith("#"):
            doc_lines.insert(0, lines[j].strip()[1:].strip())
            j -= 1
        doc_lines = [line for line in doc_lines if line]
        members = []
        i += 1
        depth_end = "End Enum" if is_enum else "End Class"
        pending_doc = []
        while i < n:
            stripped = lines[i].strip()
            if stripped == depth_end:
                break
            if stripped.startswith("#") and not stripped.startswith("##"):
                i += 1
                continue
            if stripped.startswith("##"):
                pending_doc.append(stripped[2:].strip())
                i += 1
                continue
            member = parse_member(stripped, is_enum)
            if member is not None:
                kind, signature = member
                doc = " ".join(pending_doc)
                if not is_internal_member(signature, doc):
                    members.append((kind, signature, doc))
                pending_doc = []
            elif stripped:
                pending_doc = []
            i += 1
        classes[name] = {
            "doc": doc_lines,
            "abstract": is_abstract,
            "enum": is_enum,
            "members": members,
        }
        order.append(name)
    return classes, order


def is_internal_member(signature, doc):
    """True for engine-internal members that the API reference omits.

    The compiler documents every declaration, but the module exposes some
    members purely as engine bookkeeping (scratch contexts, event buffers,
    bit sets). Their doc comments say so; the reference skips them.
    """
    if re.match(r"^m[A-Z]", signature):
        return True
    lowered = doc.lower()
    markers = (
        "engine-internal",
        "internal solver bookkeeping",
        "internal bookkeeping",
        "internal event bookkeeping",
    )
    return any(marker in lowered for marker in markers)


def parse_member(stripped, is_enum):
    """Returns (kind, signature) for a member line, or None."""
    if is_enum:
        match = re.match(r"^([A-Z][A-Za-z0-9_]*)$", stripped)
        if match:
            return ("Value", match.group(1))
        return None
    if stripped.startswith("Private ") or stripped.startswith("Pragma "):
        return None
    for prefix, kind in (
        ("Public Const ", "Constant"),
        ("Const ", "Constant"),
        ("Public Shared ", "Shared"),
        ("Shared ", "Shared"),
        ("Public Property ", "Property"),
        ("Property ", "Property"),
        ("Public Sub ", "Method"),
        ("Sub ", "Method"),
        ("Public Function ", "Method"),
        ("Function ", "Method"),
        ("Abstract Function ", "Abstract"),
        ("Abstract Sub ", "Abstract"),
        ("Constructor", "Constructor"),
    ):
        if stripped.startswith(prefix):
            signature = stripped[len(prefix):].strip()
            if prefix == "Constructor":
                signature = "Constructor" + stripped[len("Constructor"):]
            return (kind, signature)
    return None


def clean_doc(doc, name):
    """Drops cross-reference noise and collapses whitespace."""
    doc = re.sub(r"\s+", " ", doc).strip()
    doc = re.sub(r",? ported from .*$", "", doc)
    doc = re.sub(r",? matching upstream.*$", "", doc)
    doc = re.sub(r"^ported from [^.]*\.\s*", "", doc)
    doc = re.sub(r"\bupstream b2[A-Za-z0-9_]*\b", "the upstream equivalent", doc)
    doc = re.sub(r"\s+", " ", doc)
    return doc


def render_class(name, record):
    out = [f"### {name}", ""]
    doc = " ".join(record["doc"])
    doc = clean_doc(doc, name)
    if doc:
        out.append(doc)
        out.append("")
    if record["abstract"]:
        out.append("Abstract class: subclass it and override the members you need.")
        out.append("")
    if record["enum"]:
        out.append("| Value | Description |")
        out.append("|---|---|")
        for kind, signature, doc in record["members"]:
            out.append(f"| `{signature}` | {clean_doc(doc, signature)} |")
        out.append("")
        return out
    sections = {
        "Constructors": [],
        "Properties": [],
        "Shared members": [],
        "Methods": [],
        "Constants": [],
        "Values": [],
    }
    for kind, signature, doc in record["members"]:
        if kind == "Constructor":
            sections["Constructors"].append((signature, doc))
        elif kind == "Property":
            sections["Properties"].append((signature, doc))
        elif kind == "Shared":
            sections["Shared members"].append((signature, doc))
        elif kind in ("Method", "Abstract"):
            sections["Methods"].append((signature, doc))
        elif kind == "Constant":
            sections["Constants"].append((signature, doc))
        elif kind == "Value":
            sections["Values"].append((signature, doc))
    for title in ("Constructors", "Properties", "Shared members", "Methods", "Constants", "Values"):
        entries = sections[title]
        if not entries:
            continue
        out.append(f"**{title}**")
        out.append("")
        for signature, doc in entries:
            doc_text = clean_doc(doc, name)
            if doc_text:
                out.append(f"- `{signature}` — {doc_text}")
            else:
                out.append(f"- `{signature}`")
        out.append("")
    return out


def parse_module_constants():
    """Returns module-level constants as [(name, type, value, doc)] from the dist.

    Module-level members live between ``Module Physics2D`` and the first nested
    type declaration; each carries a ``##`` doc comment like every public
    member.
    """
    lines = DIST.read_text().splitlines()
    constants = []
    in_module = False
    doc_lines = []
    for line in lines:
        stripped = line.strip()
        if re.match(r"^Module\s+Physics2D\s*$", stripped, re.IGNORECASE):
            in_module = True
            continue
        if not in_module:
            continue
        if re.match(r"^(?:Abstract )?(?:Class|Enum)\s", stripped):
            break  # first nested type: module-level scope ends
        if stripped.startswith("#"):
            doc_lines.append(stripped.lstrip("#").strip())
            continue
        match = re.match(r"^Const\s+([A-Za-z_][A-Za-z0-9_]*)\s+As\s+(\w+)\s*=\s*(.+)$", stripped)
        if match:
            doc = " ".join(part for part in doc_lines if part)
            constants.append((match.group(1), match.group(2), match.group(3), doc))
        doc_lines = []
    return constants


def main():
    classes, order = parse_dist()
    problems = []
    for _, names in CATEGORIES:
        for name in names:
            if name not in classes:
                problems.append(f"curated class {name} is not in the dist")
    if problems:
        for problem in problems:
            print(f"ERROR: {problem}")
        sys.exit(1)

    lines = INTRO.splitlines()
    module_constants = parse_module_constants()
    if module_constants:
        lines.append("## Module constants")
        lines.append("")
        for name, const_type, value, doc in module_constants:
            if doc:
                lines.append(f"- `{name} As {const_type} = {value}` — {doc}")
            else:
                lines.append(f"- `{name} As {const_type} = {value}`")
        lines.append("")
    documented = set()
    for title, names in CATEGORIES:
        lines.append(f"## {title}")
        lines.append("")
        for name in names:
            lines.extend(render_class(name, classes[name]))
            documented.add(name)
        lines.append("")

    lines.append("## Internal infrastructure")
    lines.append("")
    lines.append(
        "These classes implement the engine: dense solver stores, the "
        "constraint graph, the broad phase and dynamic tree, foundation "
        "containers, and the geometry algorithms. They ship inside the "
        "module for the solver's benefit; applications use the facade "
        "API above instead. Their declarations and documentation live in "
        "the module source."
    )
    lines.append("")
    internal_names = [name for name in order if name not in documented]
    # Preserve source order, comma-separated per paragraph.
    chunk = []
    for name in internal_names:
        chunk.append(name)
    if chunk:
        lines.append(", ".join(f"`{name}`" for name in chunk) + ".")
        lines.append("")

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT} ({len(lines)} lines, {len(internal_names)} internal classes listed)")


if __name__ == "__main__":
    main()
